FROM ubuntu:latest
MAINTAINER Michael Kavulich <kavulich@ucar.edu>
#
RUN apt update
RUN apt -y install wget
RUN mkdir /gsi_data
#
# Get GSI tutorial data
#
RUN mkdir -p /gsi_data/2017051312/arw_45km \
 && wget https://dtcenter.org/com-GSI/users/tutorial/online_tutorial/releaseV3.6/data/Case01/wrfinput_d01.2017051312 -P /gsi_data/2017051312/arw_45km \
 && wget https://dtcenter.org/com-GSI/users/tutorial/online_tutorial/releaseV3.6/data/Case02/obs.tar -P /gsi_data/2017051312/ \
 && tar -xf /gsi_data/2017051312/obs.tar -C /gsi_data/2017051312/
#
# Download CRTM files
RUN wget https://dtcenter.org/com-GSI/users/downloads/GSI_releases/CRTM_v2.3.0.tar.gz -P /gsi_data/ \
 && tar -xf /gsi_data/CRTM_v2.3.0.tar.gz
VOLUME /gsi_data
CMD ["true"]
