services:
  db:
    image: mysql:5.7
    container_name: mysql_mv
    user: "mysql:mysql"
    ports:
        - "6603:3306"
    volumes:
        - ${PROJ_DIR}/metviewer/mysql:/var/lib/mysql

    environment:
        MYSQL_ROOT_PASSWORD: mvuser
    tty: true
#
  metviewer:
    image: dtcenter/nwp-container-metviewer:4.0.0
    container_name: metviewer
    ports:
    - "8080:8080"
    volumes:
      - ${PROJ_DIR}/container-dtc-nwp/components/scripts:/scripts
      - ${PROJ_DIR}/cases:/data
      - ${PROJ_DIR}/metviewer/output/xml:/opt/tomcat/webapps/metviewer_output/xml
      - ${PROJ_DIR}/metviewer/output/plots:/opt/tomcat/webapps/metviewer_output/plots
      - ${PROJ_DIR}/metviewer/output/data:/opt/tomcat/webapps/metviewer_output/data
      - ${PROJ_DIR}/metviewer/output/scripts:/opt/tomcat/webapps/metviewer_output/scripts
    links:
      - db:mysql_mv
    tty: true
#
